### PR TITLE
Improved coding standards for Storage class

### LINKED ISSUE #30: Improve Code Quality and Follow Coding Standards
Critically examines the code and refactor to improve the code quality where necessary. Tweak the code to comply with a given coding standard.

### PR DESCRIPTION
**Pull request by kwokyto**

### CODE REVIEW

**Review by SimJJ96 — APPROVED** [review]
LGTM

**Comment by joohwan58** [comment]
LGTM, thanks for the help!

**Review by joohwan58 — APPROVED** [review]
Thanks for improving my code

**Review by Vinci-Hu — APPROVED** [review]
LGTM

**Pull request merged**
